steps:
- checkout: self
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'GitHub Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: 'build.docker-compose.yml'
    action: 'Build services'
    additionalImageTags: '$(Build.BuildNumber)'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'GitHub Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: 'build.docker-compose.yml'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'